### ISSUE TITLE
Training/validation/test set

### ISSUE THREAD

**Issue by andreas-abel** [ithemal/DiffTune#2]
According to the paper, the data set was randomly split into a training, validation, and test set. Is the information which of the blocks are in which of these sets available anywhere? This information would be necessary to reproduce the results in the paper.

**Comment by alexrenda** [comment]
Hey Andreas,

the training, validation, and test split is performed here: https://github.com/ithemal/DiffTune/blob/master/difftune/runner.py#L740-L742. As long as you use the same dataset file, this should give the exact split reported in the paper.
